notifications:
    email: false

language: python
python:
    - "3.5"

before_install:
    - sudo apt-get install coinor-cbc

install:
    - pip install -r requirements.txt

script: 
    - tests/unit_tests/unit_tests.sh
    - travis_wait 180 tests/integration_tests/integration_test.sh
