notifications:
    email: false

language: python
install: travis_wait 30 mvn install
python:
    - "3.5"

before_install:
    - sudo apt-get install coinor-cbc

install:
    - pip install -r requirements.txt

script: 
    - tests/unit_tests/unit_tests.sh
    - tests/integration_tests/integration_test.sh
