notifications:
    email: false

language: python

python:
    - "3.6"

install:
    - pip install -r requirements.txt

script: 
    - tests/unit_tests/unit_tests.sh
    - tests/integration_tests/integration_test.sh
