name: pathogist
channels:
    - ibmdecisionoptimization
    - conda-forge
dependencies:
    - python >=3.5
    - numpy >=1.15.1
    - scipy >=1.1.0
    - pandas >=0.23.4
    - scikit-learn >=0.19.1
    - pyyaml >=3.13 
    - docplex >=2.7.113
    - cplex >=12.8
    - pulp >=1.6.8
    - matplotlib >=3.0.0
