name: pathogist
channels:
  - bioconda
  - conda-forge
  - ibmdecisionoptimization
dependencies:
  - python ==3.5
  - numpy >=1.15.1
  - scipy 
  - pandas >=0.23.4
  - scikit-learn >=0.19.1
  - pyyaml >=3.13
  - pulp >=1.6.8
  - networkx
  - cplex >=12.8
  - matplotlib
  - coincbc >=2.9.9
  - mentalist
  - prince
  - snippy ==3.2
  - khmer >=2.0
  - vcflib
