{% set version = "0.1" %}
package:
  name: pathogist
  version: {{ version }}

source:
  url: https://github.com/WGS-TB/PathOGiST/archive/v{{ version }}.tar.gz
  sha256: b8caa400c4ef4453902c589acf3205c2dba966f4778fae48413e2c5a70ffa3ac

build:
  number: 1
  skip: True # [osx]

requirements:
  host:
    - python ==3.5
  run:
    - python
    - numpy >=1.15.1
    - scipy >=1.1.0
    - pandas >=0.23.4
    - scikit-learn >=0.19.1
    - pyyaml >=3.13 
    - pulp >=1.6.8
    - networkx
    - cplex >=12.8
    - matplotlib
    - coincbc >=2.9.9
    - mentalist
    - prince
    - snippy

  test:
    commands:
      - pathogist -h

about:
  home: https://github.com/WGS-TB/PathOGiST
  summary: Calibrated multi-criterion genomic analysis for public health microbiology
  license: GPL-3.0
  license_file: LICENSE
