---
# PathOGiST configuration file.
# This configuration file is in YAML file format, release 1.2 (Third Edition).
# Google yaml for the specification.

# Directory to save temporary files.
temp: 
# Number of threads on your computer
threads:
# Command line options for tools to genotype your raw reads
genotyping:
    input_reads:
        forward_reads:
        reverse_reads:
    mentalist:
        build_db:
            options:
                ## kmer size
                k:
                ## FASTA files with the MLST scheme
                fasta_files:
                ## profile file for known genotypes
                profile:
        download_pubmlst:
            options:
                ## Kmer size
                k:
                ## Species name or scheme ID
                scheme:
        download_cgmlst:
            options:
                ## Kmer size
                k:
                ## Species name or scheme ID
                scheme:
        download_enterobase:
            options:
                ## Kmer size
                k:
                ## Letter identifying which scheme: 
                ## (S)almonella, (Y)ersinia, or (E)scherichia/Shigella
                scheme:
                ## Choose the type: 'cg' or 'wg' for cgMLST or wgMLST, respectively.
                type:
        call:
            options:
                ## Maximum number of mutations when looking for novel alleles 
                mutation_threshold: 6
                ## Minimum number of times a kmer is seen to be considered present in the sample 
                ## (solid)
                kt: 10
            flags:
                ## Outputs the results for the original voting algorithm. 
                #- output_votes

                ## Outputs a FASTA file with the alleles from 'special cases' such as incomplete 
                ## coverage, novel, and multiple alleles. 
                #- output_special
    kwip:
        kwip_path: 
        khmer_options:
            # k-mer size to use
            ksize: 32
            # approximate number of unique kmers in the input set
            unique-kmers: 0
        kwip_options:
            #weights:
        kwip_flags:
            #- unweighted
            #- calc_weights
    prince:
        options:
            # VNTR templates. Default is for M.TB
            #templates:
            # Kmer size used during read recruitment
            #k:
    snippy:
        options:
            # Reference genome. Supports FASTA, GenBank, EMBL (not GFF)
            reference:
            # Minimum read mapping quality to consider
            mapqual: 60
            # Minimum base quality to consider
            basequal: 20
            # Minimum coverage of variant site
            mincov: 10
            # Minimum proportion for variant evidence
            minfrac: 0.9
            # Use this @RG ID: in the bam header
            #rgid:
            # Extra BWA MEM options, e.g. -x pacbio
            #bwaopt:
        flags:
            ## Keep unmapped reads in BAM and write FASTQ.
            #- unmapped
    spotyping:
        # Path to SpoTyping.py file
        path: 
        options:
            #swift: on
            #min:
            #rmin:
            #outdir:
            #output: SpoTyping
        flags:
            #- seq
            #- noQuery
            #- filter
            #- sorted
# Do not remove the sections 'calls', 'distances', 'thresholds', 'all_constraints', or 'output'.
# Remove all key-value pairs in the sections 'calls' or 'distances' if you want them blank.
# Remove all list items in the section 'fine_clusterings' if you want that blank, too.
# Keys from 'calls' and 'distances' sections should not overlap.
clustering:
    calls: 
        # Raw genotyping data from which to create distance matrices.
        # Accepted values are paths to text files containing paths to genotyping files.
        # Currently only compatible with SNPs from snippy, MLSTs from MentaLiST, and CNVs from PRINCE
        SNP:
        MLST:
        CNV:
        spoligotyping:
    distances:
        # Paths to pre-constructed distance matrices in tsv format.
        # You can also specify SNP, MLST, spoligotypoing and CNV distance matrices here if you 
        # pre-constructed them, but then they shouldn't appear in the section 'genotyping'.
        kWIP:
    fine_clusterings:
        # The genotyping datatypes that are considered to be the "finest".
        - MLST
        - SNP
        - kWIP
    thresholds:
        # Threshold values for performing correlation clustering on genotyping data types given above
        # Every key appearing in the sections 'genotyping' and 'distances' should appear 
        # here with a value. 
        SNP: 
        MLST:
        CNV: 
        kWIP:
        spoligotyping:
    # Put the path for the final consensus clustering in tsv format here.
    output:
    # Use all constraints when performing correlation and consensus clustering
    all_constraints: False
    # Solver to use for the clustering algorithm; choices are `pulp` or `cplex`
    solver: pulp
    visualize: False
...
