---
# PathOGiST configuration file.
# This configuration file is in YAML file format, release 1.2 (Third Edition).
# Google yaml for the specification.

# Directory to save temporary files. Leave blank if you don't want to save them.
temp: 
# Number of threads on your computer
threads:
# Options for tools to genotype your raw reads
genotyping:
    input_reads:
        forward_reads:
        reverse_reads:
    mentalist:
        build_db:
            options:
                ## kmer size
                k:

                ## FASTA files with the MLST scheme
                fasta_files:

                ## profile file for known genotypes
                profile:

        download_pubmlst:
            options:
                ## Kmer size
                k:
                ## Species name or scheme ID
                scheme:
        download_cgmlst:
            options:
                ## Kmer size
                k:
                ## Species name or scheme ID
                scheme:
        download_enterobase:
            options:
                ## Kmer size
                k:
                ## Letter identifying which scheme: (S)almonella, (Y)ersinia, or (E)scherichia/Shigella
                scheme:
                ## Choose the type: 'cg' or 'wg' for cgMLST or wgMLST, respectively.
                type:
        call:
            options:
                ## Maximum number of mutations when looking for novel alleles (type: Int64, default: 6)
                mutation_threshold: 6

                ## Minimum number of times a kmer is seen to be considered present in the sample (solid)
                kt: 10

            flags:
                ## Outputs the results for the original voting algorithm. 
                ## Remove the comment to activate.
                #- output_votes

                ## Outputs a FASTA file with the alleles from 'special cases' such as 
                ## incomplete coverage,
                ## novel, and multiple alleles. 
                ## Remove the comment to activate.
                #- output_special
    kwip:
        kwip_path: 
        khmer_options:
            ksize:
            unique-kmers:
            fp-rate:
            max-memory-usage:
            small-count:
            threads:
            no-bigcount:
            summary-info:
        kwip_options:
            threads:
            kernel:
            distance:
            weights:
        kwip_flags:
            #- unweighted
            #- calc_weights

    prince:
        options:
            # output file for training data / training used to predict copy numbers for queries
            #boost_output:
            # output file for query copy number predictions
            target_output:
            # VNTR templates. Default is for M.TB
            #templates:
            # target genome names in a text file
            target_file:
            # training genome file names in a text file
            #boosting_file:
            # Kmer size used during read recruitment
            #k:
            # copy number of training genome
            #copynumber:

    snippy:
        options:
            ## RESOURCES
            #cpus: 8
            #ram: 8
            #tmpdir: /tmp
            ## INPUT
            #reference:
            #R1:
            #R2:
            #se:
            #ctgs:
            #peil:
            #bam:
            #targets:
            #subsample: 1
            ## OUTPUT
            #outdir:
            #prefix: snps
            #report:
            #cleanup:
            #rgid:
            #unmapped:
            ## PARAMETERS
            #mapqual: 60
            #basequal: 13
            #mincov: 10
            #minfrac: 0
            #minqual: 100
            #maxsoft: 10
            #bwaopt: 
            #fbopt: 

    spotyping:
        # Path to SpoTyping.py file
        path: 
        input: sample1.fastq sample2.fastq
        options:
            #swift: on
            #min:
            #rmin:
            #outdir:
            #output: SpoTyping
        flags:
            #- seq
            #- noQuery
            #- filter
            #- sorted

# Do not remove the sections 'calls', 'distances', 'thresholds', 'all_constraints', or 'output'.
# Remove all key-value pairs in the sections 'calls' or 'distances' if you want them blank.
# Remove all list items in the section 'fine_clusterings' if you want that blank, too.
# Keys from 'calls' and 'distances' sections should not overlap.
clustering:
    calls: 
        # Raw genotyping data from which to create distance matrices.
        # Accepted values are paths to text files containing paths to genotyping files.
        # Currently only compatible with SNPs from snippy, MLSTs from MentaLiST, and CNVs from PRINCE. 
        SNP:
        MLST:
        CNV:
    distances:
        # Paths to pre-constructed distance matrices in tsv format.
        # You can also specify SNP, MLST and CNV distance matrices here if you pre-constructed them,
        # but then they shouldn't appear in the section 'genotyping'.
        kmer:
        spoligo:
    fine_clusterings:
        # The genotyping datatypes that are considered to be the "finest".
        - MLST
        - SNP
        - kmer
    thresholds:
        # Threshold values for performing correlation clustering on genotyping data types given above.
        # Every key appearing in the sections 'genotyping' and 'distances' should appear here with a value. 
        SNP: 
        MLST:
        CNV: 
        kmer:
        spoligo:
    # Put the path for the final consensus clustering in tsv format here.
    output:
    # Use all constraints when performing correlation and consensus clustering
    all_constraints: False
    # Solver to use for the clustering algorithm; choices are `pulp` or `cplex`
    solver: pulp
    visualize: False
...
